### PR TITLE
Subject line

### PR DESCRIPTION
**Pull request by codi45**
Add Subject line

### CODE REVIEW

**Comment by ldmberman** [comment]
@codi45 thank you for opening a PR! I've tried it out and have some feedback.

Sending messages does not seem to work with this update. I get `TypeError: document.getElementById(...) is null` (I deployed this version [here](https://arweave.net/HQng6_Ah52z4RhSgqNuMXCn98ZUPUY1PfjFfqc1tZuc)).

Also, the transaction ID is still displayed on top of the message page while the issue description suggests it should be replaced by the subject line, which in turn should be the TX ID for now.

**Comment by codi45** [comment]
Ok  fixed Id missing and corrected subjectLine value to TX ID ;

**Comment by ldmberman** [comment]
Thank you for the update @codi45! I like how it looks and works now.

I have only two requests.

1) Could you please remove the commented out lines and format the code using our configuration for ESLint? It's very easy:

```
npm install
npx eslint --fix .
```

Ignore all the warnings it displays, just commit the changes it makes.

2) Since you have added a way to specify a subject line, it would be great to display it instead of TX ID when present. Should be a simple addition to the code.

Thank you!

**Comment by codi45** [comment]
Ok eslint --fix and subject line content display when available otherwise TX ID

**Comment by ldmberman** [comment]
@codi45 looks good, thanks!

**Pull request merged**
